"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import environ
import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 1. environ 초기화
env = environ.Env(DEBUG=(bool, False))

# 2. .env 파일 읽기
# backend/.env 경로를 정확히 잡기 위해 BASE_DIR 사용
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# 3. API KEY 로드
TMDB_API_KEY = env('TMDB_API_KEY')
KOBIS_API_KEY = env('KOBIS_API_KEY', default='')
YOUTUBE_API_KEY = env('YOUTUBE_API_KEY', default='')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7ks))u+d@^jh^_wyc2s)l7*_8r0=4u17nr0xp#0tqvxd&w6#m2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # 1. Django Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 2. Third-Party Apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'corsheaders',
    'drf_spectacular',

    # 3. Local Apps
    'accounts',
    'movies',
    'reviews',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------

# custom user model 사용
AUTH_USER_MODEL = 'accounts.User'

# Django Rest Framework 설정
REST_FRAMEWORK = {
    # 인증(Authentication): JWTAuthentication 사용
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    #TODO: 권한(Permission): 개발 중에는 편의를 위해 'AllowAny'로, 실제 서비스에선 'IsAuthenticated' 변경
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    # Swagger
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# dj-rest-auth 설정 (로그인/가입 로직)
REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_COOKIE': 'movwa-access',
    'JWT_AUTH_REFRESH_COOKIE': 'movwa-refresh',
    # [중요] 닉네임 처리용 Serializer 연결
    'REGISTER_SERIALIZER': 'accounts.serializers.CustomRegisterSerializer',
    'USER_DETAILS_SERIALIZER': 'accounts.serializers.CustomUserDetailsSerializer',
}

# Allauth 설정 (필수)
SITE_ID = 1  # django.contrib.sites가 사용하는 사이트 식별자

# 로그인 방법: 이메일만 사용
ACCOUNT_LOGIN_METHODS = {'email'}

# TODO: 이메일 인증 메일 보내기 (개발 중엔 none)
ACCOUNT_EMAIL_VERIFICATION = 'none'

# 회원가입 필드 설정 (최신 방식)
# 비밀번호는 알아서 처리되므로 적지 않습니다.
ACCOUNT_SIGNUP_FIELDS = [
    'email',    # 이메일 받음
    'username', # 핸들(아이디) 받음
    # 'nickname', # 닉네임은 별도 Serializer에서 처리(실무 방법)하거나 여기서 추가
]

# 핸들/이메일 필수 여부
ACCOUNT_UNIQUE_EMAIL = True

# Simple JWT 설정 (토큰 유효기간 등)
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # 액세스 토큰 1시간
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),     # 리프레시 토큰 1일
}

# CORS 설정 (프론트엔드 통신 허용)
# TODO: 나중에 Vue 개발 서버 주소(예: localhost:5173)를 여기에 추가
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",    # Vite(Vue) 기본 포트
    "http://localhost:8080",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:8080",
]

# 경고 무시 설정
# "이메일 로그인인데 왜 username 입력받냐" -> 경고(W001)
# username을 '로그인 ID'가 아니라 '보여주기용 핸들'로 쓰기 때문 -> 경고 무시
SILENCED_SYSTEM_CHECKS = ['account.W001']

# Swagger 설정
SPECTACULAR_SETTINGS = {
    'TITLE': 'MOVWA API',
    'DESCRIPTION': 'Movwa 영화 추천 서비스 API 문서입니다.',
    'VERSION': '1.0.0',
    'SCHEMA_PATH_PREFIX': '/api/v1/',
    'SERVE_INCLUDE_SCHEMA': False,
    # SWAGGER UI 설정
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True, # 새로고침 해도 인증 정보(토큰) 유지
        'displayOperationId': True,   # 각 API의 고유 ID 표시
    },
}

# [Static files] (CSS, JS, 로고 등 개발자가 만든 파일)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # 프로덕션용 (python manage.py collectstatic)

# [Media files] (프로필 이미지 등 사용자가 업로드한 파일)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')