# Generated by Django 5.2.9 on 2025-12-24 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxOfficeRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('rank_type', models.CharField(choices=[('daily', '일간'), ('weekly', '주간')], default='daily', max_length=20)),
                ('date', models.DateField()),
                ('audience_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxoffice_ranks', to='movies.movie')),
            ],
            options={
                'ordering': ['date', 'rank'],
                'indexes': [models.Index(fields=['rank_type', 'date', 'rank'], name='movies_boxo_rank_ty_ad4982_idx')],
                'constraints': [models.UniqueConstraint(fields=('movie', 'rank_type', 'date'), name='unique_movie_rank_type_date')],
            },
        ),
    ]
